export enum Type {
  Blend = 1,
  Bloom = 2,
  Bokeh = 3,
  BrightnessContrast = 4,
  Ssao = 5,
  Sepia = 6,
  Vignette = 7,
  Luminosity = 8,
  HueSaturation = 9,
  EdgeDetect = 10,
  Fxaa = 11,
  HorizontalTiltShift = 12,
  VerticalTiltShift = 13,
  MotionBlur = 14,
}
